version: "3.7"

services:
  dev_postgres:
    container_name: dev_playground_postgres
    image: postgres:12.4-alpine
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data

  dev_node_graphql_apollo:
    container_name: dev_playground_node_graphql_apollo
    command: npm run serve
    build:
      context: ../projects/node-graphql-apollo
      dockerfile: ./configs/Dockerfile.dev
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_USER
    ports:
      - "4000:4000"
    volumes:
      - ../projects/node-graphql-apollo:/app:cached
      - /app/node_modules
      - ../.vscode:/app/.vscode
    depends_on:
      - dev_postgres

  dev_react:
    container_name: dev_playground_react
    command: npm run docker:develop
    stdin_open: true
    build:
      context: ../projects/react
      dockerfile: ./configs/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../projects/react:/app:cached
      - /app/node_modules
      - ../.vscode:/app/.vscode

  dev_react_gatsby:
    container_name: dev_playground_react_gatsby
    command: npm run docker:develop
    build:
      context: ../projects/react-gatsby
      dockerfile: ./configs/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../projects/react-gatsby:/app:cached
      - /app/node_modules
      - ../.vscode:/app/.vscode
