version: "3.7"

services:
  postgres:
    container_name: playground_postgres
    image: postgres:12.4-alpine
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.9
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "8880:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - node_graphql_apollo
      - angular
      - react
      - react_gatsby
      - vue

  node_graphql_apollo:
    container_name: playground_node_graphql_apollo
    command: npm run serve
    build:
      context: ../projects/node-graphql-apollo
      dockerfile: ./configs/Dockerfile
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_USER
    ports:
      - "4000:4000"
    volumes:
      - ../projects/node-graphql-apollo:/app:cached
      - ../.vscode:/app/.vscode
      - /app/node_modules
    depends_on:
      - postgres

  angular:
    container_name: playground_angular
    command: npm run docker
    build:
      context: ../projects/angular
      dockerfile: ./configs/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ../projects/angular:/app:cached
      - ../.vscode:/app/.vscode
      - /app/node_modules

  react:
    container_name: playground_react
    command: npm run docker
    build:
      context: ../projects/react
      dockerfile: ./configs/Dockerfile
    environment:
      - PUBLIC_URL=react
    ports:
      - "3000:3000"
    volumes:
      - ../projects/react:/app:cached
      - ../.vscode:/app/.vscode
      - /app/node_modules

  react_gatsby:
    container_name: playground_react_gatsby
    command: npm run docker
    build:
      context: ../projects/react-gatsby
      dockerfile: ./configs/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../projects/react-gatsby:/app:cached
      - ../.vscode:/app/.vscode
      - /app/node_modules

  vue:
    container_name: playground_vue
    command: npm run docker
    build:
      context: ../projects/vue
      dockerfile: ./configs/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../projects/vue:/app:cached
      - ../.vscode:/app/.vscode
      - /app/node_modules
